### ISSUE TITLE
Should language definition be by object or by attribute? 

### ISSUE THREAD

**Issue by wonderchook** [opensupplyhub/supplychaindata.exchange#4]
Does it make sense to have the language of the data be in the knowledge object or by individual data attribute?

Example would be a case where a factory has names in multiple languages. Should it be possible to have infinite languages for one location?

**Comment by fredsourcing** [comment]
"Should it be possible to have infinite languages for one location?" Yes, I believe this will be required.

For example I looked at how the LEI handles this after you shared the link on Slack and they accept an unlimited number of translated names.

It might also make sense to have an "alias" table with unlimited records for each organization that can be used for the purpose of deduplication (i.e. if a duplicate has been found then store in alias table)
