### ISSUE TITLE
Thread on different kinds of identifiers to include

### ISSUE THREAD

**Issue by shuyag** [opensupplyhub/supplychaindata.exchange#8]
An interesting case that might warrant needing to add a country field into the organization schema, in the case of a tax ID being used for the organization-id, which would help to specify which one it's referencing. 

Using the SCDEX to show associations (for example, a merge between two organization) might be an interesting outcome of being allowed to append multiple org-ids. We should probably follow a principle of being more "generous" with the kinds of IDs that are referenced and allowed, because then this works as a way to cross reference different IDs referencing the same organization.

**Comment by shuyag** [comment]
For example, Brazil uses tax ids on most official documents to reference an organization, whereas in China, the Chinese Corporate Social Credit Number is used across most documents.

**Comment by vasgat** [comment]
I agree with being more generous with the identifiers. I would prefer a facility or organization to have any identifier rather than none at all.

**Comment by shuyag** [comment]
Merge this issue with the one here on sector, location, etc! https://github.com/opensupplyhub/supplychaindata.exchange/issues/5
